import type { Instrument } from "./market-data/types";

export const MARKET_OVERVIEW_INSTRUMENTS: Instrument[] = [
  {
    symbol: "S&P 500",
    providerSymbol: "^GSPC",
    name: "S&P 500",
    exchange: "SNP",
    currency: "USD",
    type: "index",
  },
  {
    symbol: "ASX 200",
    providerSymbol: "^AXJO",
    name: "S&P/ASX 200",
    exchange: "ASX",
    currency: "AUD",
    type: "index",
  },
  {
    symbol: "BTC",
    providerSymbol: "BTC-USD",
    name: "Bitcoin",
    exchange: "CCC",
    currency: "USD",
    type: "crypto",
  },
];

export const DEFAULT_WATCHLIST: Instrument[] = [
  {
    symbol: "GOOGL",
    providerSymbol: "GOOGL",
    name: "Alphabet Inc.",
    exchange: "NASDAQ",
    currency: "USD",
    type: "equity",
  },
  {
    symbol: "NFLX",
    providerSymbol: "NFLX",
    name: "Netflix Inc.",
    exchange: "NASDAQ",
    currency: "USD",
    type: "equity",
  },
  {
    symbol: "BRK-B",
    providerSymbol: "BRK-B",
    name: "Berkshire Hathaway B",
    exchange: "NYSE",
    currency: "USD",
    type: "equity",
  },
  {
    symbol: "DJCO",
    providerSymbol: "DJCO",
    name: "Daily Journal Corp.",
    exchange: "NASDAQ",
    currency: "USD",
    type: "equity",
  },
  {
    symbol: "BABA",
    providerSymbol: "BABA",
    name: "Alibaba Group",
    exchange: "NYSE",
    currency: "USD",
    type: "equity",
  },
  {
    symbol: "AI1",
    providerSymbol: "AI1.AX",
    name: "Airtasker Ltd",
    exchange: "ASX",
    currency: "AUD",
    type: "equity",
  },
  {
    symbol: "CTD",
    providerSymbol: "CTD.AX",
    name: "Corporate Travel Mgmt",
    exchange: "ASX",
    currency: "AUD",
    type: "equity",
  },
  {
    symbol: "PRX",
    providerSymbol: "PRX.AS",
    name: "Prosus N.V.",
    exchange: "AMS",
    currency: "EUR",
    type: "equity",
  },
  {
    symbol: "AAPL",
    providerSymbol: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    currency: "USD",
    type: "equity",
  },
  {
    symbol: "MSFT",
    providerSymbol: "MSFT",
    name: "Microsoft Corp.",
    exchange: "NASDAQ",
    currency: "USD",
    type: "equity",
  },
  {
    symbol: "AMZN",
    providerSymbol: "AMZN",
    name: "Amazon.com Inc.",
    exchange: "NASDAQ",
    currency: "USD",
    type: "equity",
  },
];
